### ISSUE TITLE
Error: "Service lacks both ExecStart= and ExecStop= setting. Refusing."

### ISSUE THREAD

**Issue by birdybro** [justinegeffen/mattermost_raspberrypi_recipe#3]
Distro used: 2019-04-08-raspbian-stretch-lite.img

I went back and tried out the latest version of Raspbian Stretch lite as your guide hasn't been updated for Buster and was receiving this same error I'm reporting now. This happens in both stretch and buster so far. This is what happens on the "Set up Mattermost to Use systemd for Starting and Stopping." section.

```
pi@raspberrypi:/opt/mattermost $ sudo systemctl status mattermost.service
● mattermost.service
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Dec 31 19:38:01 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:1] Assignment outside of section. Ignoring.
Dec 31 19:38:01 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:2] Assignment outside of section. Ignoring.
Dec 31 19:38:01 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:3] Assignment outside of section. Ignoring.
Dec 31 19:38:01 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:4] Assignment outside of section. Ignoring.
Dec 31 19:38:01 raspberrypi systemd[1]: mattermost.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Dec 31 19:38:10 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:1] Assignment outside of section. Ignoring.
Dec 31 19:38:10 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:2] Assignment outside of section. Ignoring.
Dec 31 19:38:10 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:3] Assignment outside of section. Ignoring.
Dec 31 19:38:10 raspberrypi systemd[1]: [/lib/systemd/system/mattermost.service:4] Assignment outside of section. Ignoring.
Dec 31 19:38:10 raspberrypi systemd[1]: mattermost.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

I tried adding the following:

ExecStart=/opt/mattermost/bin/mattermost

But that did nothing, I get the same error.

https://www.freedesktop.org/software/systemd/man/systemd.unit.html

According to the manpage, some of the formatting may be very specific, if this helps.

**Comment by amgibson2** [comment]
I also have this issue.

**Comment by esbeeb** [comment]
This one works for me.  Note I use MariaDB, not Mysql.  just change "mariadb" to "mysql" in your case:

[Unit]
Description=Mattermost
After=network.target
After=mariadb.service
Requires=mariadb.service

[Service]
Type=notify
ExecStart=/opt/mattermost/bin/mattermost
TimeoutStartSec=3600
Restart=always
RestartSec=10
WorkingDirectory=/opt/mattermost
User=mattermost
Group=mattermost
LimitNOFILE=49152

[Install]
WantedBy=multi-user.target

**Comment by esbeeb** [comment]
I basically got this from the official Mattermost documentation, seen here:
https://docs.mattermost.com/install/install-debian.html#installing-mattermost-server
See step 9 there.

**Comment by esbeeb** [comment]
The headings "[Unit]" and "[Service]" were absent...

@justinegeffen , would you please add those 2 headings, as above?  Those are needed in buster.

**Comment by justinegeffen** [comment]
> The headings "[Unit]" and "[Service]" were absent...
> 
> @justinegeffen , would you please add those 2 headings, as above? Those are needed in buster.

Hi, @esbeeb. Thanks for picking that up. I've just merged a PR which included those changes. Let me know if that resolves your request?

**Comment by esbeeb** [comment]
Yes, solved.

**Comment by birdybro** [comment]
I will test it out when I get a chance, thanks for addressing the issue. On work from home status at the moment.
