### ISSUE TITLE
Lets Encrypt SSL

### ISSUE THREAD

**Issue by amgibson2** [justinegeffen/mattermost_raspberrypi_recipe#4]
Could you help me with setting up SSL also ?

**Comment by justinegeffen** [comment]
Hi @amgibson2. Would you be open to providing more details about the issue you're having? I can also recommend posting your question [on the forum](https://forum.mattermost.org/t/raspberry-pi-4-mattermost-inside-docker/8112/4) as there may be other community members who have had the same question and received assistance.
