### ISSUE TITLE
Adding postgresql version setup

### ISSUE THREAD

**Issue by seiwonpark** [justinegeffen/mattermost_raspberrypi_recipe#6]
Do you consider adding document of setting by postgresql?

e.g. we got newest version v.7.5.2 from https://github.com/SmartHoneybee/ubiquitous-memory/releases/

and more about database settings

**Comment by justinegeffen** [comment]
Thanks for the suggestion. I am not maintaining or updating this content at the moment. If that changes I'll definitely look into it. :) :)
